### ISSUE TITLE
Modul-Unterstützung

### ISSUE THREAD

**Issue by area-net-gmbh** [appcms/server#37]
Aufteilung (oder als zusätzliche Option) des custom-Ordners in Modulen, um bei größeren Projekten die Übersichtlichkeit zu bewahren.

* custom
* modules
** modul1
** modul2
** ...

Jedes Modul besitzt dabei den gleichen/ähnlichen Aufbau/Logik wie der custom-Ordner, plus zusätzlich einer Installationsroutine, um z.B. assets-Ordner freizugeben (Symlink in public-Ordner).

**Comment by areanet-schmid** [comment]
Zurückgestellt.
