### ISSUE TITLE
Anlegen von Ordnern nicht möglich

### ISSUE THREAD

**Issue by areanet-patzak** [appcms/server#91]
Fehler beim Anlegen von Ordner in der Medienverwaltung:

`An exception occurred while executing 'UPDATE pim_tree SET sorting = sorting + 1 WHERE (id) IN (SELECT id FROM pim_tree_id_tmp)': SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '='`

**Comment by areanet-schmid** [comment]
Kann nicht reproduziert werden.
